name: "CI"

on: 
    push:
        paths: ~
    workflow_dispatch: ~

jobs:
    hello:
        runs-on: "ubuntu-latest"
        name: "Hello"
        steps:
            - name: "Hello world"
              run: echo "Hello, world!"
            - name: "multiple  world"
              run: |
                echo "Say"
                exit 1
                echo "Hello"
              continue-on-error: true
            - name: "list files"
              run: ls