name: "CI"

on:
  push:
    paths-ignore: "./ci-basics.yml"
  workflow_dispatch: ~

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      # - name: "PHPStan"
      #   uses: docker://oskarstark/phpstan-ga
      #   with:
      #     args: analyse tests/ --level=9

      - name: Install "PHP_CodeSniffer"
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: Novusvetus/action-php_codesniffer@1.2.17
        with:
          files: "**.php"
          scan_all: true
          phpcs_path: php phpcs.phar
          standard: phpcs.xml 

  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    services:
      database:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.1
          tools: composer
      - name: "Check database healthy"
        run: nc -zv localhost 3306
      - name: "Install composer deps"
        run: |
          export APP_ENV=test
          composer install --prefer-dist --no-interaction --no-progress
      - name: "Run migrations"
        run: |
          php bin/console d:m:m
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: app
          DATABASE_PASSWORD: password
      - name: "Start server"
      # php bin/console server:start
        run: |
          php bin/console
          php -S 127.0.0.1:8080 -t public &
          sleep 2
          nc -zv localhost 8080
    